# Generated by Django 5.2.6 on 2025-11-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communitypost",
            name="board",
        ),
        migrations.RemoveField(
            model_name="communitycomment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="communitycomment",
            name="post",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="community_comment",
        ),
        migrations.RemoveField(
            model_name="communitypost",
            name="author",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="class_comment",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="event",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.DeleteModel(
            name="CommunityBoard",
        ),
        migrations.DeleteModel(
            name="CommunityComment",
        ),
        migrations.DeleteModel(
            name="CommunityPost",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
