# Generated by Django 5.2.6 on 2025-12-02 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_faqcategory_faqitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faqitem",
            name="category",
        ),
        migrations.DeleteModel(
            name="FAQCategory",
        ),
        migrations.DeleteModel(
            name="FAQItem",
        ),
    ]
