# Generated by Django 5.2.6 on 2025-11-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="강의 종료일"),
        ),
        migrations.AddField(
            model_name="class",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="강의 시작일"),
        ),
    ]
