# Generated by Django 5.2.6 on 2025-11-29 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityBoard",
            fields=[
                ("board_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "board_title",
                    models.CharField(max_length=100, verbose_name="게시판 제목"),
                ),
                (
                    "board_type",
                    models.CharField(max_length=20, verbose_name="게시판 유형"),
                ),
            ],
            options={
                "verbose_name": "커뮤니티 게시판",
                "verbose_name_plural": "커뮤니티 게시판 목록",
                "db_table": "community_board",
            },
        ),
        migrations.CreateModel(
            name="CommunityPost",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("post_title", models.CharField(max_length=100, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                ("open", models.BooleanField(default=True, verbose_name="공개 여부")),
                ("view", models.IntegerField(default=0, verbose_name="조회수")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="board.communityboard",
                        verbose_name="게시판",
                    ),
                ),
            ],
            options={
                "verbose_name": "커뮤니티 게시글",
                "verbose_name_plural": "커뮤니티 게시글 목록",
                "db_table": "community_post",
            },
        ),
        migrations.CreateModel(
            name="CommunityComment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment_content", models.TextField(verbose_name="댓글 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="board.communitypost",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "커뮤니티 댓글",
                "verbose_name_plural": "커뮤니티 댓글 목록",
                "db_table": "community_comment",
            },
        ),
    ]
