# Generated by Django 5.2.6 on 2025-11-30 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_communityboard_communitypost_communitycomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitycomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="board.communitycomment",
            ),
        ),
    ]
